import { type Project, type Opportunity } from "@/types";

export const CURRENT_USER = {
  id: "user1",
  name: "山田美咲",
  image:
    "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fotor%20AI%20Image%20Creator%20Nov%2030%20(3).jpg-v7ifi1e9jgGZ756DbfeIZ8sO5wzaqA.jpeg",
};

export const mockInvitationOpportunities: Opportunity[] = [
  {
    id: "bbq-1",
    title: "小豆島おもてなしBBQ",
    description: "地元の食材を使ったBBQで観光客をおもてなし！",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    startsAt: "2025-02-15T10:00:00.000Z",
    endsAt: "2025-02-15T15:00:00.000Z",
    location: {
      name: "小豆島オリーブ公園",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
    host: {
      name: "山田太郎",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host1",
      title: "地域活性化コンサルタント",
      bio: "10年以上にわたり、全国各地の地域活性化プロジェクトに携わってきました。",
    },
    capacity: 10,
    participants: [],
    image: "/placeholder.svg",
    recommendedFor: [
      "地域活性化に興味がある方",
      "BBQが好きな方",
      "小豆島の魅力を発信したい方",
    ],
  },
] as const;

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "地域で持続可能なビジネスをつくるには？",
    description:
      "地域で持続可能なビジネスを作るためのポイントについて、地域事業者と専門家が議論します。地域資源の活用、マーケティング戦略、資金調達など、実践的な内容を多角的に解説します。\n\n形式：パネルディスカッション（40分議論 + 20分Q&A）\n対象：プロジェクトや地域活性に興味がある人",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host1",
    startsAt: "2025-02-01T13:00:00+09:00",
    endsAt: "2025-02-01T14:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "山田太郎",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host1",
      title: "地域活性化コンサルタント",
      bio: "10年以上にわたり、全国各地の地域活性化プロジェクトに携わってきました。",
    },
    capacity: 5,
    participants: [
      CURRENT_USER,
      {
        id: "user2",
        name: "鈴木花子",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user2",
      },
      {
        id: "user3",
        name: "田中健一",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user3",
      },
      {
        id: "user4",
        name: "渡辺美咲",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user4",
      },
      {
        id: "user5",
        name: "小林誠",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user5",
      },
    ],
    recommendedFor: [
      "知多、西三河エリアで観光に関する業務を実践、興味がある方",
      "発酵文化にまつわる事業を行われている方",
      "食文化を基軸にしたインバウンド観光に関係する方",
    ],
    relatedArticles: [
      {
        title: "折山尚美：地域活性化の新しい形を求めて",
        url: "/interviews/oriyama",
        type: "interview",
        image: "/placeholder.svg",
        description:
          "結婚を契機に南信州へ移住され、今や地域に欠くことのできない存在。飲食店や古民家・文化財の活用などを通じて地域活性にまつわる幅広い活動に携わる原動力について伺いました。",
        publishedAt: "2024/01/16",
      },
      {
        title: "小豆島オリーブが繋ぐ、地域の未来",
        url: "/articles/shodoshima-olive-future",
        type: "article",
        image: "/placeholder.svg",
        description:
          "小豆島のオリーブ栽培の歴史と、新しい取り組みについて紹介します。",
        publishedAt: "2024/01/15",
      },
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島図学館",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "2",
    title: "観光業と地域課題解決の両立",
    description:
      "観光業を通じた地域課題解決の可能性について、実例を交えながら紹介します。持続可能な観光モデルの構築方法や、地域コミュニティとの協働についてお話しします。",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host2",
    startsAt: "2025-02-01T15:00:00+09:00",
    endsAt: "2025-02-01T16:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "鈴木美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host2",
      title: "観光まちづくりプランナー",
      bio: "地域の魅力を活かした持続可能な観光開発を提案しています。",
    },
    capacity: 30,
    participants: [
      {
        id: "user6",
        name: "山本健一",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user6",
      },
    ],
    recommendedFor: [
      "観光業に携わる方",
      "地域活性化に興味のある方",
      "まちづくりに関心のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "善通寺",
      address: "香川県善通寺市",
      isOnline: false,
    },
  },
  {
    id: "3",
    title: "古民家再生プロジェクトの清掃サポート",
    description:
      "古民家を活用したコミュニティスペースの清掃作業のお手伝いを募集しています。地域の方々と交流しながら、古民家の魅力を体感できます。",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host3",
    startsAt: "2025-02-02T10:00:00+09:00",
    endsAt: "2025-02-02T15:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "田中美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host3",
      title: "古民家再生プロジェクトマネージャー",
      bio: "地域の古民家を活用した新しいコミュニティづくりを行っています。",
    },
    capacity: 10,
    pointsForComplete: 500,
    participants: [],
    recommendedFor: [
      "地域の歴史や文化に興味のある方",
      "古民家の再生に関心のある方",
      "地域コミュニティに参加したい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "旧山田家住宅",
      address: "香川県高松市",
      isOnline: false,
    },
  },
  {
    id: "4",
    title: "若手農家が語る：小豆島オリーブの未来",
    description:
      "地域の若手農家が小豆島のオリーブ栽培の未来について語ります。新しい栽培方法や、オリーブを活用した地域活性化の取り組みについて紹介します。",
    type: "EVENT",
    status: "closed",
    projectId: "shodoshima-olive",
    hostId: "host3",
    startsAt: "2025-01-15T15:00:00+09:00",
    endsAt: "2025-01-15T16:00:00+09:00",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    host: {
      name: "木村健一",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host3",
      title: "オリーブ農家",
      bio: "小豆島で3代目のオリーブ農家として活動しています。",
    },
    capacity: 30,
    participants: [CURRENT_USER],
    recommendedFor: [
      "農業に興味がある方",
      "地域活性化に関心のある方",
      "オリーブについて学びたい方",
    ],
    relatedArticles: [
      {
        title: "小豆島オリーブが繋ぐ、地域の未来",
        url: "/articles/shodoshima-olive-future",
        type: "article",
        image: "/placeholder.svg",
        description:
          "小豆島のオリーブ栽培の歴史と、新しい取り組みについて紹介します。",
        publishedAt: "2024/01/15",
      },
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島オリーブ公園",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "shikoku-pilgrimage-quest-1",
    title: "四国遍路案内アプリのベータテスター募集",
    description:
      "開発中の四国遍路案内アプリのベータ版テストにご協力いただける方を募集します。実際に札所を巡りながら、アプリの使い勝手や改善点をフィードバックしていただきます。",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host4",
    startsAt: "2025-02-03T09:00:00+09:00",
    endsAt: "2025-02-03T17:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "中村太郎",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host4",
      title: "アプリ開発プロジェクトマネージャー",
      bio: "地域の文化をテクノロジーで支援するプロジェクトを推進しています。",
    },
    capacity: 5,
    pointsForComplete: 1000,
    participants: [],
    recommendedFor: [
      "四国遍路に興味のある方",
      "アプリ開発に関心のある方",
      "地域の文化デジタル化に興味のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "善通寺周辺",
      address: "香川県善通寺市",
      isOnline: false,
    },
  },
  {
    id: "shodoshima-olive-event-1",
    title: "若手農家が語る：小豆島オリーブの未来",
    description:
      "小豆島で新しくオリーブ栽培を始めた若手農家たちが、その魅力と課題、そして未来への展望を語ります。",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host5",
    startsAt: "2025-02-04T15:00:00+09:00",
    endsAt: "2025-02-04T16:30:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "木村花子",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host5",
      title: "オリーブ農家",
      bio: "3年前から小豆島でオリーブ栽培を始めました。",
    },
    capacity: 20,
    participants: [],
    recommendedFor: [
      "農業に興味のある方",
      "小豆島の地域活性に関心のある方",
      "オリーブ栽培について知りたい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島オリーブ公園",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "shodoshima-olive-quest-1",
    title: "オリーブを使った新商品開発ワークショップ",
    description:
      "小豆島のオリーブ農園で収穫体験をしながら、新商品のアイデアを考えるワークショップを開催します。収穫したオリーブを使って実際に商品化も目指します。",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host6",
    startsAt: "2025-02-05T13:00:00+09:00",
    endsAt: "2025-02-05T16:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "高橋誠",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host6",
      title: "商品開発マネージャー",
      bio: "地域の特産品を活かした商品開発に携わっています。",
    },
    capacity: 15,
    pointsForComplete: 800,
    participants: [],
    recommendedFor: [
      "商品開発に興味のある方",
      "オリーブに関心のある方",
      "ものづくりが好きな方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島オリーブ研究所",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "shikoku-food-event-1",
    title: "デジタルで守る：四国の食文化と技",
    description:
      "四国の伝統的な食文化をデジタルで記録・保存する意義と手法について、食文化研究者とデジタルアーカイブの専門家が解説します。\n\n形式：パネルディスカッション（60分）",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host7",
    startsAt: "2025-02-06T14:00:00+09:00",
    endsAt: "2025-02-06T15:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "佐々木健一",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host7",
      title: "食文化研究者",
      bio: "四国の伝統的な食文化の研究と記録に取り組んでいます。",
    },
    capacity: 30,
    participants: [],
    recommendedFor: [
      "食文化に興味のある方",
      "デジタルアーカイブに関心のある方",
      "地域の伝統を守りたい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "オンライン",
      address: "",
      isOnline: true,
      meetingUrl: "https://meet.google.com/xxx-xxxx-xxx",
    },
  },
  {
    id: "shikoku-food-quest-1",
    title: "郷土料理のデジタルアーカイブ作成",
    description:
      "地域のお年寄りから伝統的な郷土料理のレシピを聞き取り、デジタル化するボランティアを募集します。料理の写真撮影や動画記録もお願いします。\n\n形式：2-3時間の取材活動",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host8",
    startsAt: "2025-02-07T10:00:00+09:00",
    endsAt: "2025-02-07T13:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "山口美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host8",
      title: "デジタルアーキビスト",
      bio: "文化財のデジタル保存・活用に携わっています。",
    },
    capacity: 5,
    pointsForComplete: 600,
    participants: [],
    recommendedFor: [
      "料理が好きな方",
      "地域の食文化に興味のある方",
      "写真・動画撮影ができる方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "高松市民センター",
      address: "香川県高松市",
      isOnline: false,
    },
  },
  {
    id: "naoshima-sauna-quest-1",
    title: "サウナで使う薪を取りに行こう",
    description: "直島の里山で薪拾いをしながら、持続可能なサウナ運営について学びます。集めた薪は実際にサウナで使用されます。\n\n形式：フィールドワーク（3時間程度）",
    type: "QUEST",
    status: "open",
    projectId: "naoshima-sauna",
    hostId: "host9",
    startsAt: "2025-02-10T09:00:00+09:00",
    endsAt: "2025-02-10T12:00:00+09:00",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    host: {
      name: "木村隆",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host9",
      title: "サウナプロデューサー",
      bio: "サステナブルなサウナ文化の普及に取り組んでいます。",
    },
    capacity: 8,
    pointsForComplete: 400,
    participants: [],
    recommendedFor: [
      "サウナ好きな方",
      "自然の中での活動が好きな方",
      "持続可能な観光に興味のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "直島サウナ",
      address: "香川県香川郡直島町",
      isOnline: false,
    },
    relatedArticles: [
      {
        title: "直島の里山が育むサウナ文化",
        url: "/articles/naoshima-sauna-culture",
        type: "article",
        image: "/placeholder.svg",
        description: "アートの島として知られる直島で、新たに注目を集めるサステナブルなサウナの取り組みについて紹介します。",
        publishedAt: "2024/01/20",
      },
      {
        title: "木村隆：サウナから考える持続可能な観光",
        url: "/interviews/kimura-takashi",
        type: "interview",
        image: "/placeholder.svg",
        description: "直島サウナプロジェクトを立ち上げた木村氏に、サウナを通じた新しい観光の形について語っていただきました。",
        publishedAt: "2024/01/21",
      }
    ],
  },
  {
    id: "naoshima-sauna-event-1",
    title: "サウナの薪割り・火おこし体験",
    description: "直島サウナで実際に薪割りと火おこしを体験。火を通じて、人とサウナの関係を考えます。\n\n形式：体験型ワークショップ（2時間）",
    type: "EVENT",
    status: "open",
    projectId: "naoshima-sauna",
    hostId: "host10",
    startsAt: "2025-02-11T14:00:00+09:00",
    endsAt: "2025-02-11T16:00:00+09:00",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    host: {
      name: "山田健一",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host10",
      title: "火おこしマイスター",
      bio: "伝統的な火おこしの技術を継承しています。",
    },
    capacity: 10,
    participants: [],
    recommendedFor: [
      "サウナ文化に興味のある方",
      "火おこしを学びたい方",
      "持続可能な暮らしに関心のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "直島サウナ",
      address: "香川県香川郡直島町",
      isOnline: false,
    },
    relatedArticles: [
      {
        title: "火のある暮らしを見つめ直す",
        url: "/articles/life-with-fire",
        type: "article",
        image: "/placeholder.svg",
        description: "現代社会で失われつつある「火を使う技術」の大切さと、それを守り継ぐ人々の取り組みを紹介します。",
        publishedAt: "2024/01/22",
      }
    ],
  },
  {
    id: "uchiko-renovation-event-1",
    title: "合同会社型DAOが古民家再生の資金調達を変える",
    description: "ブロックチェーン技術を活用した新しい資金調達の形について、実例を交えながら解説します。\n\n形式：パネルディスカッション（60分）",
    type: "EVENT",
    status: "open",
    projectId: "uchiko-renovation",
    hostId: "host11",
    startsAt: "2025-02-12T19:00:00+09:00",
    endsAt: "2025-02-12T20:00:00+09:00",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    host: {
      name: "佐藤健一",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host11",
      title: "DAO研究家",
      bio: "Web3技術の地域活性化への応用を研究しています。",
    },
    capacity: 30,
    participants: [],
    recommendedFor: [
      "古民家再生に興味のある方",
      "DAOやWeb3に関心のある方",
      "新しい資金調達の形を探している方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "オンライン",
      address: "",
      isOnline: true,
      meetingUrl: "https://meet.google.com/xxx-xxxx-xxx",
    },
    relatedArticles: [
      {
        title: "地域活性化とDAO：新しい可能性",
        url: "/articles/dao-regional-development",
        type: "article",
        image: "/placeholder.svg",
        description: "DAOの仕組みを活用した地域活性化の最新事例と、その可能性について解説します。",
        publishedAt: "2024/01/10",
      },
      {
        title: "古民家×ブロックチェーン最前線",
        url: "/articles/blockchain-traditional-houses",
        type: "article",
        image: "/placeholder.svg",
        description: "伝統的な建造物の保存と活用に、ブロックチェーン技術がもたらす新しい可能性を探ります。",
        publishedAt: "2024/01/11",
      }
    ],
  },
  {
    id: "uchiko-renovation-quest-1",
    title: "古民家の清掃・メンテナンス",
    description: "内子町の古民家を清掃し、簡単な補修作業を行います。古民家の維持管理の基礎を学べます。\n\n形式：実地作業（4時間）",
    type: "QUEST",
    status: "open",
    projectId: "uchiko-renovation",
    hostId: "host12",
    startsAt: "2025-02-13T09:00:00+09:00",
    endsAt: "2025-02-13T13:00:00+09:00",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    host: {
      name: "高橋美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host12",
      title: "建築家",
      bio: "古民家の再生と活用をテーマに活動しています。",
    },
    capacity: 12,
    pointsForComplete: 500,
    participants: [],
    recommendedFor: [
      "古民家に興味のある方",
      "DIYが好きな方",
      "地域の歴史的建造物を守りたい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "内子町並み保存地区",
      address: "愛媛県喜多郡内子町",
      isOnline: false,
    },
    relatedArticles: [
      {
        title: "高橋美咲：建築家が語る古民家の魅力",
        url: "/interviews/takahashi-misaki",
        type: "interview",
        image: "/placeholder.svg",
        description: "内子町で古民家再生に取り組む建築家・高橋美咲氏に、古民家の持つ可能性について伺いました。",
        publishedAt: "2024/01/12",
      }
    ],
  },
  {
    id: "tokushima-maze-event-1",
    title: "迷路のまちナイトツアー",
    description: "眉山の傾斜地に広がる路地を、ライトアップとともに巡ります。地域の方々との交流も楽しめます。\n\n形式：ガイド付きツアー（2時間）",
    type: "EVENT",
    status: "open",
    projectId: "tokushima-maze",
    hostId: "host13",
    startsAt: "2025-02-14T18:00:00+09:00",
    endsAt: "2025-02-14T20:00:00+09:00",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    host: {
      name: "中村誠",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host13",
      title: "まちづくりコーディネーター",
      bio: "地域の魅力を活かした体験型観光を企画しています。",
    },
    capacity: 15,
    participants: [],
    recommendedFor: [
      "徳島の路地裏に興味のある方",
      "ナイトツアーが好きな方",
      "地域の方々と交流したい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "眉山ロープウェイ駅前",
      address: "徳島県徳島市",
      isOnline: false,
    },
    relatedArticles: [
      {
        title: "夜の徳島、新しい魅力",
        url: "/articles/tokushima-night",
        type: "article",
        image: "/placeholder.svg",
        description: "眉山の傾斜地に広がる路地裏の夜の表情と、そこで生まれる新しいコミュニティについて紹介します。",
        publishedAt: "2024/01/25",
      },
      {
        title: "中村誠：迷路のまちが繋ぐ人々の物語",
        url: "/interviews/nakamura-makoto",
        type: "interview",
        image: "/placeholder.svg",
        description: "徳島の路地裏を活かしたまちづくりに取り組む中村氏に、プロジェクトの背景と展望を伺いました。",
        publishedAt: "2024/01/26",
      }
    ],
  },
  {
    id: "tokushima-maze-quest-1",
    title: "観光マップの更新作業",
    description: "路地裏の新しい観光スポットや、おすすめの撮影ポイントを調査し、マップを更新します。\n\n形式：フィールドワーク（3時間）",
    type: "QUEST",
    status: "open",
    projectId: "tokushima-maze",
    hostId: "host14",
    startsAt: "2025-02-15T13:00:00+09:00",
    endsAt: "2025-02-15T16:00:00+09:00",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    host: {
      name: "田中美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host14",
      title: "地域ガイド",
      bio: "徳島の路地裏の魅力を発信しています。",
    },
    capacity: 6,
    pointsForComplete: 300,
    participants: [],
    recommendedFor: [
      "街歩きが好きな方",
      "写真撮影が得意な方",
      "地域の魅力発信に興味のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "徳島市観光案内所",
      address: "徳島県徳島市",
      isOnline: false,
    },
    relatedArticles: [
      {
        title: "進化する観光マップの作り方",
        url: "/articles/evolving-tourist-map",
        type: "article",
        image: "/placeholder.svg",
        description: "地域の魅力を伝える観光マップの作り方と、デジタル時代における新しい可能性について解説します。",
        publishedAt: "2024/01/27",
      }
    ],
  }
];

export const mockProjects: Project[] = [
  {
    id: "shodoshima-olive",
    title: "小豆島オリーブプロジェクト",
    description: "小豆島の伝統的なオリーブ栽培を次世代へ",
    icon: "/placeholder.svg",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    members: [
      {
        id: "member1",
        name: "田中健一",
        title: "プロジェクトリーダー",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member1",
      },
    ],
    opportunities: [],
    socialLinks: [
      { type: "instagram", url: "https://instagram.com/shodoshima_olive" },
      { type: "website", url: "https://shodoshima-olive.jp" },
    ],
  },
  {
    id: "setouchi-art",
    title: "瀬戸内アートプロジェクト",
    description: "アートを通じて瀬戸内の魅力を発信",
    icon: "/placeholder.svg",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    members: [
      {
        id: "member2",
        name: "山本美咲",
        title: "アートディレクター",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member2",
      },
    ],
    opportunities: [],
    socialLinks: [
      { type: "instagram", url: "https://instagram.com/setouchi_art" },
      { type: "twitter", url: "https://twitter.com/setouchi_art" },
    ],
  },
  {
    id: "kagawa-local-food",
    title: "かがわ食文化プロジェクト",
    description: "香川の伝統的な食文化を守り、発信する",
    icon: "/placeholder.svg",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    members: [
      {
        id: "member3",
        name: "佐藤直子",
        title: "食文化研究家",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member3",
      },
    ],
    opportunities: [],
    socialLinks: [
      { type: "youtube", url: "https://youtube.com/@kagawa_food" },
      { type: "website", url: "https://kagawa-food.jp" },
    ],
  },
  {
    id: "naoshima-sauna",
    title: "直島サウナプロジェクト",
    description: "アートの島でサステナブルなサウナ文化を育む",
    icon: "/placeholder.svg",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    members: [
      {
        id: "member4",
        name: "木村隆",
        title: "サウナプロデューサー",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member4",
      },
    ],
    opportunities: [],
    socialLinks: [
      { type: "instagram", url: "https://instagram.com/naoshima_sauna" },
      { type: "website", url: "https://naoshima-sauna.jp" },
    ],
  },
  {
    id: "uchiko-renovation",
    title: "内子町古民家再生プロジェクト",
    description: "歴史的な町並みを活かした新しいコミュニティづくり",
    icon: "/placeholder.svg",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    members: [
      {
        id: "member5",
        name: "高橋美咲",
        title: "建築家",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member5",
      },
    ],
    opportunities: [],
    socialLinks: [
      { type: "instagram", url: "https://instagram.com/uchiko_renovation" },
      { type: "website", url: "https://uchiko-renovation.jp" },
    ],
  },
  {
    id: "tokushima-maze",
    title: "徳島迷路のまちづくり",
    description: "眉山の傾斜地に広がる路地を活かした体験型観光",
    icon: "/placeholder.svg",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    members: [
      {
        id: "member6",
        name: "中村誠",
        title: "まちづくりコーディネーター",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member6",
      },
    ],
    opportunities: [],
    socialLinks: [
      { type: "instagram", url: "https://instagram.com/tokushima_maze" },
      { type: "website", url: "https://tokushima-maze.jp" }
    ]
  }
];
