import { type Project, type Opportunity } from "@/types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "地域で持続可能なビジネスをつくるには？",
    description:
      "地域で持続可能なビジネスを作るためのポイントについて、地域事業者と専門家が議論します。地域資源の活用、マーケティング戦略、資金調達など、実践的な内容を多角的に解説します。\n\n形式：パネルディスカッション（40分議論 + 20分Q&A）\n対象：プロジェクトや地域活性に興味がある人",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host1",
    startsAt: "2025-02-01T13:00:00+09:00",
    endsAt: "2025-02-01T14:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "山田太郎",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host1",
      title: "地域活性化コンサルタント",
      bio: "10年以上にわたり、全国各地の地域活性化プロジェクトに携わってきました。",
    },
    capacity: 5,
    participants: [
      {
        id: "user1",
        name: "山田美咲",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fotor%20AI%20Image%20Creator%20Nov%2030%20(3).jpg-v7ifi1e9jgGZ756DbfeIZ8sO5wzaqA.jpeg",
      },
      {
        id: "user2",
        name: "鈴木花子",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user2",
      },
      {
        id: "user3",
        name: "田中健一",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user3",
      },
      {
        id: "user4",
        name: "渡辺美咲",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user4",
      },
      {
        id: "user5",
        name: "小林誠",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user5",
      },
    ],
    recommendedFor: [
      "知多、西三河エリアで観光に関する業務を実践、興味がある方",
      "発酵文化にまつわる事業を行われている方",
      "食文化を基軸にしたインバウンド観光に関係する方",
    ],
    relatedArticles: [
      {
        title: "折山尚美：地域活性化の新しい形を求めて",
        url: "/interviews/oriyama",
        type: "interview",
        image: "/placeholder.svg",
        description:
          "結婚を契機に南信州へ移住され、今や地域に欠くことのできない存在。飲食店や古民家・文化財の活用などを通じて地域活性にまつわる幅広い活動に携わる原動力について伺いました。",
        publishedAt: "2024/01/16",
      },
      {
        title: "小豆島オリーブが繋ぐ、地域の未来",
        url: "/articles/shodoshima-olive-future",
        type: "article",
        image: "/placeholder.svg",
        description:
          "小豆島のオリーブ栽培の歴史と、新しい取り組みについて紹介します。",
        publishedAt: "2024/01/15",
      },
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島図学館",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "2",
    title: "観光業と地域課題解決の両立",
    description:
      "観光業を通じた地域課題解決の可能性について、実例を交えながら紹介します。持続可能な観光モデルの構築方法や、地域コミュニティとの協働についてお話しします。",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host2",
    startsAt: "2025-02-01T15:00:00+09:00",
    endsAt: "2025-02-01T16:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "鈴木美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host2",
      title: "観光まちづくりプランナー",
      bio: "地域の魅力を活かした持続可能な観光開発を提案しています。",
    },
    capacity: 30,
    participants: [
      {
        id: "user6",
        name: "山本健一",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=user6",
      },
    ],
    recommendedFor: [
      "観光業に携わる方",
      "地域活性化に興味のある方",
      "まちづくりに関心のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "善通寺",
      address: "香川県善通寺市",
      isOnline: false,
    },
  },
  {
    id: "3",
    title: "古民家再生プロジェクトの清掃サポート",
    description:
      "古民家を活用したコミュニティスペースの清掃作業のお手伝いを募集しています。地域の方々と交流しながら、古民家の魅力を体感できます。",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host3",
    startsAt: "2025-02-02T10:00:00+09:00",
    endsAt: "2025-02-02T15:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "田中美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host3",
      title: "古民家再生プロジェクトマネージャー",
      bio: "地域の古民家を活用した新しいコミュニティづくりを行っています。",
    },
    capacity: 10,
    pointsForComplete: 500,
    participants: [],
    recommendedFor: [
      "地域の歴史や文化に興味のある方",
      "古民家の再生に関心のある方",
      "地域コミュニティに参加したい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "旧山田家住宅",
      address: "香川県高松市",
      isOnline: false,
    },
  },
  {
    id: "4",
    title: "若手農家が語る：小豆島オリーブの未来",
    description:
      "地域の若手農家が小豆島のオリーブ栽培の未来について語ります。新しい栽培方法や、オリーブを活用した地域活性化の取り組みについて紹介します。",
    type: "EVENT",
    status: "closed",
    projectId: "shodoshima-olive",
    hostId: "host3",
    startsAt: "2025-01-15T15:00:00+09:00",
    endsAt: "2025-01-15T16:00:00+09:00",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    host: {
      name: "木村健一",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host3",
      title: "オリーブ農家",
      bio: "小豆島で3代目のオリーブ農家として活動しています。",
    },
    capacity: 30,
    participants: [
      {
        id: "user1",
        name: "山田美咲",
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fotor%20AI%20Image%20Creator%20Nov%2030%20(3).jpg-v7ifi1e9jgGZ756DbfeIZ8sO5wzaqA.jpeg",
      },
    ],
    recommendedFor: [
      "農業に興味がある方",
      "地域活性化に関心のある方",
      "オリーブについて学びたい方",
    ],
    relatedArticles: [
      {
        title: "小豆島オリーブが繋ぐ、地域の未来",
        url: "/articles/shodoshima-olive-future",
        type: "article",
        image: "/placeholder.svg",
        description:
          "小豆島のオリーブ栽培の歴史と、新しい取り組みについて紹介します。",
        publishedAt: "2024/01/15",
      },
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島オリーブ公園",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "shikoku-pilgrimage-quest-1",
    title: "四国遍路案内アプリのベータテスター募集",
    description:
      "開発中の四国遍路案内アプリのベータ版テストにご協力いただける方を募集します。実際に札所を巡りながら、アプリの使い勝手や改善点をフィードバックしていただきます。",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host4",
    startsAt: "2025-02-03T09:00:00+09:00",
    endsAt: "2025-02-03T17:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "中村太郎",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host4",
      title: "アプリ開発プロジェクトマネージャー",
      bio: "地域の文化をテクノロジーで支援するプロジェクトを推進しています。",
    },
    capacity: 5,
    pointsForComplete: 1000,
    participants: [],
    recommendedFor: [
      "四国遍路に興味のある方",
      "アプリ開発に関心のある方",
      "地域の文化デジタル化に興味のある方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "善通寺周辺",
      address: "香川県善通寺市",
      isOnline: false,
    },
  },
  {
    id: "shodoshima-olive-event-1",
    title: "若手農家が語る：小豆島オリーブの未来",
    description:
      "小豆島で新しくオリーブ栽培を始めた若手農家たちが、その魅力と課題、そして未来への展望を語ります。",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host5",
    startsAt: "2025-02-04T15:00:00+09:00",
    endsAt: "2025-02-04T16:30:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "木村花子",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host5",
      title: "オリーブ農家",
      bio: "3年前から小豆島でオリーブ栽培を始めました。",
    },
    capacity: 20,
    participants: [],
    recommendedFor: [
      "農業に興味のある方",
      "小豆島の地域活性に関心のある方",
      "オリーブ栽培について知りたい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島オリーブ公園",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "shodoshima-olive-quest-1",
    title: "オリーブを使った新商品開発ワークショップ",
    description:
      "小豆島のオリーブ農園で収穫体験をしながら、新商品のアイデアを考えるワークショップを開催します。収穫したオリーブを使って実際に商品化も目指します。",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host6",
    startsAt: "2025-02-05T13:00:00+09:00",
    endsAt: "2025-02-05T16:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "高橋誠",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host6",
      title: "商品開発マネージャー",
      bio: "地域の特産品を活かした商品開発に携わっています。",
    },
    capacity: 15,
    pointsForComplete: 800,
    participants: [],
    recommendedFor: [
      "商品開発に興味のある方",
      "オリーブに関心のある方",
      "ものづくりが好きな方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "小豆島オリーブ研究所",
      address: "香川県小豆郡小豆島町",
      isOnline: false,
    },
  },
  {
    id: "shikoku-food-event-1",
    title: "デジタルで守る：四国の食文化と技",
    description:
      "四国の伝統的な食文化をデジタルで記録・保存する意義と手法について、食文化研究者とデジタルアーカイブの専門家が解説します。\n\n形式：パネルディスカッション（40分議論 + 20分Q&A）",
    type: "EVENT",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host7",
    startsAt: "2025-02-06T14:00:00+09:00",
    endsAt: "2025-02-06T15:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "佐々木健一",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host7",
      title: "食文化研究者",
      bio: "四国の伝統的な食文化の研究と記録に取り組んでいます。",
    },
    capacity: 30,
    participants: [],
    recommendedFor: [
      "食文化に興味のある方",
      "デジタルアーカイブに関心のある方",
      "地域の伝統を守りたい方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "オンライン",
      address: "",
      isOnline: true,
      meetingUrl: "https://meet.google.com/xxx-xxxx-xxx",
    },
  },
  {
    id: "shikoku-food-quest-1",
    title: "郷土料理のデジタルアーカイブ作成",
    description:
      "地域のお年寄りから伝統的な郷土料理のレシピを聞き取り、デジタル化するボランティアを募集します。料理の写真撮影や動画記録もお願いします。\n\n形式：2-3時間の取材活動",
    type: "QUEST",
    status: "open",
    projectId: "shodoshima-olive",
    hostId: "host8",
    startsAt: "2025-02-07T10:00:00+09:00",
    endsAt: "2025-02-07T13:00:00+09:00",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    host: {
      name: "山口美咲",
      image: "https://api.dicebear.com/7.x/personas/svg?seed=host8",
      title: "デジタルアーキビスト",
      bio: "文化財のデジタル保存・活用に携わっています。",
    },
    capacity: 5,
    pointsForComplete: 600,
    participants: [],
    recommendedFor: [
      "料理が好きな方",
      "地域の食文化に興味のある方",
      "写真・動画撮影ができる方",
    ],
    image: "/placeholder.svg",
    location: {
      name: "高松市民センター",
      address: "香川県高松市",
      isOnline: false,
    },
  },
];

export const mockProjects: Project[] = [
  {
    id: "shodoshima-olive",
    title: "小豆島オリーブ×次産業化プロジェクト",
    description:
      "小豆島のオリーブを活用した新しい産業創出を目指すプロジェクト。地域の伝統と革新を組み合わせ、持続可能な地域経済の発展を目指します。",
    icon: "/placeholder.svg",
    members: [
      {
        id: "member1",
        name: "山田太郎",
        title: "プロジェクトリーダー",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member1",
      },
      {
        id: "member2",
        name: "鈴木花子",
        title: "地域コーディネーター",
        image: "https://api.dicebear.com/7.x/personas/svg?seed=member2",
      },
    ],
    socialLinks: [
      {
        type: "instagram",
        url: "https://www.instagram.com/shodoshima_olive",
      },
      {
        type: "website",
        url: "https://shodoshima-olive.jp",
      },
      {
        type: "youtube",
        url: "https://youtube.com/@shodoshima_olive",
      },
    ],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    opportunities: mockOpportunities,
  },
];
